CREATE TABLE customer (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
aggregateid VARCHAR(40) NOT NULL UNIQUE,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
address VARCHAR(50) NOT NULL,
email VARCHAR(30) NOT NULL UNIQUE,
)